# Generated by Django 4.0.1 on 2022-01-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('priority__gt', 0)), name='priority_gt_0'),
        ),
    ]
